name: whatsapp_unilink
description: Dart package helping your app interact with WhatsApp via HTTP links (universal links). Works with Flutter.
homepage: https://github.com/dartsidedev/whatsapp_unilink
issue_tracker: https://github.com/dartsidedev/whatsapp_unilink/issues
version: 2.0.1+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13
scripts: derry.yaml
